web_app/config/routes.rb
Rails.application.routes.draw do
  root "policies#index"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :policies, only: [:new, :create, :show, :index]

  resources :payments, only: [:new, :create]
  get "payments/success"
  get "payments/cancel"

  mount ActionCable.server => "/cable"
  post "/live_confirm", to: "payments#live_confirm"
  post "/stripe/webhooks", to: "payments#receive"
end

web_app/app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  before_action :authenticate_user!
  include Graphql::Sender
  def index
    sleep(1)
    return nil if policies_list.nil?
    @policies = policies_list
  end

  def new
  end

  def create
    session = Stripe::Checkout::Session.create(
      payment_method_types: ["card"],
      line_items: [{
        price: "price_1P8SotKmqF3g59MYAA9dsfGv",
        quantity: 1
      }],
      mode: "payment",
      success_url: payments_success_url,
      cancel_url: payments_cancel_url
    )

    payment_id = session.id
    payment_url = session.url

    send_to_graphql(Graphql::Mutations.create_policy(params, payment_id, payment_url))

    redirect_to policies_path
  end

  def show
    redirect_to policies_path
  end

  private

  def policies_list
    response = send_to_graphql(Graphql::Queries.get_policies)
    return nil if response.parsed_response.dig("data", "policies").nil?
    response
      .parsed_response
      .dig("data", "policies")
      .map { |hash| hash.with_indifferent_access }
  end
end

web_app/app/views/policies/index.html.erb
<div class="home-container">
  <h1>Home</h1>
  <% if current_user %>
  <h2><%= "Hello " + current_user.name %></h2>
  <%= link_to "Edit Account", edit_user_registration_path, class: "home-link" %>
  <h3>Policies List</h3>
  <% if @policies %>
    <table class="home-table">
      <thead>
        <th>ID</th>
        <th>Insured Name</th>
        <th>CPF</th>
        <th>Vehicle Plate</th>
        <th>Vehicle Brand and Model</th>
        <th>Insured at</th>
        <th>Insured until</th>
        <th>Status</th>
        <th>Payment Link</th>
      </thead>
      <tbody>
        <% @policies.each do |policy| %>
          <tr>
            <td><%= policy[:id] %></td>
            <td><%= policy[:insured][:name] %></td>
            <td><%= policy[:insured][:cpf] %></td>
            <td><%= policy[:vehicle][:plate] %></td>
            <td><%= policy[:vehicle][:brand] %> <%= policy[:vehicle][:model] %></td>
            <td><%= policy[:issuedDate] %></td>
            <td><%= policy[:endCoverageDate] %></td>
            <td><%= policy[:status] %></td>
            <td style="max-width: 200px; overflow: hidden;">
              <% if policy[:status] == 'active' %>
                Paid
              <% else %>
                <a href="<%= policy[:paymentLink] %>" target="_blank"><%= policy[:paymentLink] %></a>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% else %>
      <p> No Policies were found </p>
    <% end %>
  <%= link_to 'Create Policy', new_policy_path, class: "home-link" %>
  <%= button_to "Logout", destroy_user_session_path,class: "home-button", data: {turbo: false}, method: :delete %>
  <% else %>
    <%= link_to "Login", new_user_session_path %>
    <%= link_to "Create Account", new_user_registration_path %>
  <%end%>
</div>

web_app/app/views/policies/new.html.erb
<div class="home-container">
  <h2>CREATE POLICY</h2>
  <div style="margin: 0px auto; max-width: 720px;" class="container">
    <%= form_with url: policies_path do |form| %>
      <div class="field">
        <%= form.label :insured_name, 'Name', class: 'label' %>
        <%= form.text_field :insured_name, required: true, class: 'field input' %>
      </div>

      <div class="field">
        <%= form.label :insured_cpf, 'CPF', class: 'label' %>
        <%= form.text_field :insured_cpf, required: true, class: 'input' %>
      </div>
  
      <div class="field">
        <%= form.label :issued_date, 'Insured at:', class: 'label' %>
        <%= form.date_field :issued_date,required: true, class: 'input' %>
      </div>

      <div class="field">
        <%= form.label :end_coverage_date, 'Insured Until:', class: 'label' %>
        <%= form.date_field :end_coverage_date,required: true, class: 'input' %>
      </div>

      <div class="field">
        <%= form.label :vehicle_plate, 'Vehicle Plate:', class: 'label' %>
        <%= form.text_field :vehicle_plate, required: true, class: 'input' %>
      </div>

      <div class="field">
        <%= form.label :vehicle_brand, 'Vehicle Brand:', class: 'label' %>
        <%= form.text_field :vehicle_brand, required: true, class: 'input' %>
      </div>

      <div class="field">
        <%= form.label :vehicle_model, 'Vehicle Model:', class: 'label' %>
        <%= form.text_field :vehicle_model, required: true, class: 'input' %>
      </div>

      <div class="field">
        <%= form.label :vehicle_year, 'Vehicle Year:', class: 'label' %>
        <%= form.number_field :vehicle_year, required: true, class: 'input' %>
      </div>

      <div class="actions">
        <br />
        <%= form.submit 'Create Policy' %>
      </div>
    <% end %>
  </div>
</div>